# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('serial_number', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Only 16 char length, hex values are allowed.', regex='^[0-9A-F]{16}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveIntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('maximum_capacity', models.PositiveIntegerField(default=1)),
                ('number_of_requests', models.PositiveIntegerField(default=0)),
                ('camera', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera.Camera')),
            ],
        ),
    ]
