# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 14:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-F]{16}$', 'Only 16 length, hex values are allowed.')])),
            ],
        ),
    ]
