# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('camera', '0001_initial'), ('camera', '0002_room'), ('camera', '0003_auto_20171118_1557'), ('camera', '0004_auto_20171118_1600'), ('camera', '0005_auto_20171118_2312'), ('camera', '0006_measurement'), ('camera', '0007_measurement_camera'), ('camera', '0008_auto_20171118_2355'), ('camera', '0009_remove_measurement_camera')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-F]{16}$', 'Only 16 length, hex values are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('camera', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera.Camera')),
                ('maximum_capacity', models.PositiveIntegerField(default=1)),
                ('number_of_requests', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Only 16 char length, hex values are allowed.', regex='^[0-9A-F]{16}$')]),
        ),
        migrations.RemoveField(
            model_name='camera',
            name='id',
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Only 16 char length, hex values are allowed.', regex='^[0-9A-F]{16}$')]),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
    ]
