# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
