# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 15:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='maximum_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Only 16 char length, hex values are allowed.', regex='^[0-9A-F]{16}$')]),
        ),
    ]
