# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20171118_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='camera',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera.Camera'),
        ),
    ]
