# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_auto_20171118_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='id',
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Only 16 char length, hex values are allowed.', regex='^[0-9A-F]{16}$')]),
        ),
    ]
