# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='camera',
            field=models.ForeignKey(default=datetime.datetime(2017, 11, 18, 23, 51, 42, 159686, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='camera.Camera'),
            preserve_default=False,
        ),
    ]
