# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_measurement_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
