# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_auto_20171118_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='camera',
        ),
    ]
